name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t vibe-docker-test .
      - name: Docker smoke test
        run: |
          docker run --rm vibe-docker-test --help || true
